"""initial: pgvector extension and core tables

Revision ID: d38ba57bebea
Revises: 
Create Date: 2026-05-23 16:01:14.666960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'd38ba57bebea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('project_name', sa.String(length=256), nullable=True),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=256), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_documents_user_id'), 'career_documents', ['user_id'], unique=False)
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=False),
    sa.Column('position', sa.String(length=256), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('job_url', sa.String(length=2048), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_user_id'), 'job_applications', ['user_id'], unique=False)
    op.create_table('user_llm_configs',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('encrypted_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_assignments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('essay_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('char_target', sa.Integer(), nullable=False),
    sa.Column('tone', sa.String(length=64), nullable=True),
    sa.Column('persona', sa.String(length=128), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_essay_library_application_id'), 'essay_library', ['application_id'], unique=False)
    op.create_index(op.f('ix_essay_library_user_id'), 'essay_library', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS vector")
    op.drop_index(op.f('ix_essay_library_user_id'), table_name='essay_library')
    op.drop_index(op.f('ix_essay_library_application_id'), table_name='essay_library')
    op.drop_table('essay_library')
    op.drop_table('user_llm_configs')
    op.drop_index(op.f('ix_job_applications_user_id'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_career_documents_user_id'), table_name='career_documents')
    op.drop_table('career_documents')
    # ### end Alembic commands ###
